package com.serhat.autosub.ui.main;

import android.content.res.Configuration; import android.graphics.Color; import android.media.MediaMetadataRetriever; import android.net.Uri; import android.os.Bundle; import android.view.View; import android.widget.Toast;
import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.NonNull; import androidx.appcompat.app.AppCompatActivity; import androidx.fragment.app.Fragment; import androidx.lifecycle.ViewModelProvider;
import com.serhat.autosub.R; import com.serhat.autosub.cortaja.ui.*; import com.serhat.autosub.databinding.ActivityMainBinding; import com.serhat.autosub.queue.QueueItem; import com.serhat.autosub.shorts.ShortsReviewFragment;
import java.util.Collections; import java.util.function.Consumer;

public class MainActivity extends AppCompatActivity {
    private ActivityMainBinding binding; private MainViewModel viewModel; private boolean pipelineStarted; private Consumer<Uri> pickerCallback;
    private final ActivityResultLauncher<String[]> picker = registerForActivityResult(new ActivityResultContracts.OpenDocument(), uris -> { if (uris != null && pickerCallback != null) pickerCallback.accept(uris); });
    @Override protected void onCreate(Bundle state){ super.onCreate(state); binding=ActivityMainBinding.inflate(getLayoutInflater()); setContentView(binding.getRoot()); viewModel=new ViewModelProvider(this).get(MainViewModel.class); getSupportActionBar(); configureMenu(); binding.bottomNavigation.setOnItemSelectedListener(item->{showTab(item.getItemId()); return true;}); observePipeline(); if(state==null) showTab(R.id.nav_generate); }
    private void configureMenu(){ binding.toolbar.setTitle("CortaJá"); binding.bottomNavigation.getMenu().findItem(R.id.nav_generate).setTitle("Início"); binding.bottomNavigation.getMenu().findItem(R.id.nav_models).setTitle("Projetos"); binding.bottomNavigation.getMenu().findItem(R.id.nav_exports).setTitle("Meus Cortes"); binding.bottomNavigation.getMenu().findItem(R.id.nav_settings).setTitle("Configurações"); }
    private void showTab(int id){ Fragment f; String title; if(id==R.id.nav_models){f=new ProjectsFragment(); title="Projetos";} else if(id==R.id.nav_exports){f=new MyCutsFragment(); title="Meus Cortes";} else if(id==R.id.nav_settings){f=new CortaJaSettingsFragment(); title="Configurações";} else {f=new HomeFragment(); title="CortaJá";} binding.toolbar.setTitle(title); getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,f).commit(); }
    public void openNewProject(){ binding.toolbar.setTitle("Novo projeto"); getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new NewProjectFragment()).addToBackStack("novo_projeto").commit(); }
    public void pickLocalVideo(Consumer<Uri> callback){ pickerCallback=callback; picker.launch(new String[]{"video/*"}); }
    public void startCortaJaAnalysis(Uri uri){ pipelineStarted=false; binding.toolbar.setTitle("Análise"); getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new AnalysisFragment()).commit(); viewModel.addVideosToQueue(Collections.singletonList(uri), this::displayName, this::isVertical); }
    private void observePipeline(){ viewModel.getQueueItems().observe(this, items->{ if(pipelineStarted || items==null) return; for(QueueItem item:items){ if(item.getStatus()==QueueItem.Status.COMPLETED){ pipelineStarted=true; viewModel.analyzeShorts(item,5,15,60,"Melhores momentos",false,false); break; } if(item.getStatus()==QueueItem.Status.FAILED){ pipelineStarted=true; Toast.makeText(this,"Não foi possível processar este vídeo.",Toast.LENGTH_LONG).show(); } } }); viewModel.getShortsProject().observe(this,p->{ if(pipelineStarted && p!=null && !p.getCandidates().isEmpty()){ binding.toolbar.setTitle("Melhores cortes"); viewModel.prepareShorts(viewModel.getSelectedQueueItem().getValue()); getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new ShortsReviewFragment()).commit(); } }); }
    private String displayName(Uri uri){ return uri == null ? "Vídeo" : (uri.getLastPathSegment()==null ? "Vídeo" : uri.getLastPathSegment()); }
    private boolean isVertical(Uri uri){ try{MediaMetadataRetriever r=new MediaMetadataRetriever();r.setDataSource(this,uri);String w=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH),h=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT);r.release();return Integer.parseInt(h)>Integer.parseInt(w);}catch(Exception e){return false;} }
}
