package com.serhat.autosub.ui.main;

import android.media.MediaMetadataRetriever; import android.net.Uri; import android.os.Bundle; import android.widget.Toast;
import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.appcompat.app.AppCompatActivity; import androidx.fragment.app.Fragment; import androidx.lifecycle.ViewModelProvider;
import com.serhat.autosub.R; import com.serhat.autosub.core.DebugLog; import com.serhat.autosub.cortaja.source.PublicVideoSourceResolver; import com.serhat.autosub.cortaja.source.YtDlpSourceResolver; import com.serhat.autosub.cortaja.source.AndroidYtDlpClient; import com.serhat.autosub.cortaja.source.YtDlpRuntime; import com.serhat.autosub.cortaja.source.SourceResolution; import com.serhat.autosub.cortaja.source.PublicMediaRoutingPolicy; import com.serhat.autosub.cortaja.ui.*; import com.serhat.autosub.databinding.ActivityMainBinding; import com.serhat.autosub.queue.QueueItem; import com.serhat.autosub.shorts.ShortsReviewFragment;
import java.util.Collections; import java.util.function.Consumer;

public class MainActivity extends AppCompatActivity {
    private ActivityMainBinding binding; private MainViewModel viewModel; private boolean pipelineStarted; private Consumer<Uri> pickerCallback; private Uri pendingUri; private String pendingTitle="Vídeo";
    private final ActivityResultLauncher<String[]> picker=registerForActivityResult(new ActivityResultContracts.OpenDocument(),u->{if(u!=null&&pickerCallback!=null)pickerCallback.accept(u);});
    @Override protected void onCreate(Bundle state){super.onCreate(state);binding=ActivityMainBinding.inflate(getLayoutInflater());setContentView(binding.getRoot());viewModel=new ViewModelProvider(this).get(MainViewModel.class);configureMenu();binding.bottomNavigation.setOnItemSelectedListener(item->{showTab(item.getItemId());return true;});observePipeline();if(state==null)showTab(R.id.nav_generate);}
    private void configureMenu(){binding.toolbar.setTitle("CortaJá");binding.bottomNavigation.getMenu().findItem(R.id.nav_generate).setTitle("Início");binding.bottomNavigation.getMenu().findItem(R.id.nav_models).setTitle("Projetos");binding.bottomNavigation.getMenu().findItem(R.id.nav_exports).setTitle("Meus Cortes");binding.bottomNavigation.getMenu().findItem(R.id.nav_settings).setTitle("Configurações");}
    private void showTab(int id){Fragment f;String title;if(id==R.id.nav_models){f=new ProjectsFragment();title="Projetos";}else if(id==R.id.nav_exports){f=new MyCutsFragment();title="Meus Cortes";}else if(id==R.id.nav_settings){f=new CortaJaSettingsFragment();title="Configurações";}else{f=new HomeFragment();title="CortaJá";}binding.toolbar.setTitle(title);getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,f).commit();}
    public void openNewProject(){binding.toolbar.setTitle("Novo projeto");getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new NewProjectFragment()).addToBackStack("novo_projeto").commit();}
    public void pickLocalVideo(Consumer<Uri> callback){pickerCallback=callback;picker.launch(new String[]{"video/*"});}
    public void startCortaJaLinkAnalysis(String url){binding.toolbar.setTitle("Preparando mídia");getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new AnalysisFragment()).commit();new Thread(() -> {try{YtDlpRuntime.initializeBlocking(this);new YtDlpSourceResolver(new AndroidYtDlpClient(this)).resolveAsync(url,new YtDlpSourceResolver.Callback(){@Override public void onResolved(SourceResolution r,String v){runOnUiThread(() -> startResolved(r));}@Override public void onError(String e){runOnUiThread(() -> resolveWithNativeFallback(url,e));}});}catch(Exception e){runOnUiThread(() -> resolveWithNativeFallback(url,e.getMessage()));}}).start();}
    private void startResolved(SourceResolution r){if(r==null||!r.hasUsableMedia()){showLinkError("A plataforma não forneceu uma mídia pública utilizável.");return;}pendingTitle=r.title;DebugLog.i("CortaJaRoute","provider="+r.provider+" sourceId="+r.sourceId+" durationMs="+r.durationMs+" sourceUrl="+safePublicUrl(r.sourceUrl)+" mediaUrlPresent="+(!r.mediaUrl.isEmpty())+" audioUrlPresent="+(!r.audioUrl.isEmpty()));PublicMediaRoutingPolicy.Route route=PublicMediaRoutingPolicy.route(r);DebugLog.i("CortaJaRoute","pipeline="+route);if(route==PublicMediaRoutingPolicy.Route.PUBLIC_YTDLP){pipelineStarted=true;String publicSource=r.sourceUrl.isEmpty()?(r.mediaUrl.isEmpty()?r.audioUrl:r.mediaUrl):r.sourceUrl;viewModel.startLongVodAnalysis(publicSource,r.durationMs,new AndroidYtDlpClient(this).version());return;}if(route==PublicMediaRoutingPolicy.Route.LIVE_UNAVAILABLE){showLinkError("Live reconhecida; o pipeline incremental ainda não está disponível para esta fonte.");return;}if(route!=PublicMediaRoutingPolicy.Route.LOCAL_FILE){showLinkError("Não foi possível determinar uma mídia pública utilizável.");return;}startCortaJaAnalysis(Uri.parse(r.sourceUrl.isEmpty()?(r.mediaUrl.isEmpty()?r.audioUrl:r.mediaUrl):r.sourceUrl));}
    private void resolveWithNativeFallback(String url,String originalError){new PublicVideoSourceResolver().resolveAsync(url,new PublicVideoSourceResolver.Callback(){public void onResolved(SourceResolution r){runOnUiThread(() -> startResolved(r));}public void onError(String e){runOnUiThread(() -> showLinkError(e==null?originalError:e));}});}
    public void startCortaJaAnalysis(Uri uri){if(PublicMediaRoutingPolicy.isRemote(uri)){showLinkError("Mídia HTTP pública deve ser processada pelo resolvedor yt-dlp.");return;}pipelineStarted=false;pendingUri=uri;binding.toolbar.setTitle("Análise");getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new AnalysisFragment()).commit();viewModel.addVideosToQueue(Collections.singletonList(uri),u->pendingTitle,this::isVertical);}
    private void showLinkError(String e){pipelineStarted=true;Toast.makeText(this,e==null?"Não foi possível resolver este link público.":e,Toast.LENGTH_LONG).show();binding.toolbar.setTitle("CortaJá");showTab(R.id.nav_generate);}
    private void observePipeline(){viewModel.getQueueItems().observe(this,items->{if(pipelineStarted||items==null||pendingUri==null)return;for(QueueItem item:items){if(item.getVideoUri()!=null&&!pendingUri.equals(item.getVideoUri()))continue;if(item.getStatus()==QueueItem.Status.COMPLETED){pipelineStarted=true;viewModel.analyzeShorts(item,5,15,60,"Melhores momentos",false,false);break;}if(item.getStatus()==QueueItem.Status.FAILED){pipelineStarted=true;Toast.makeText(this,"Falha ao processar mídia: " + (item.getMessage()==null||item.getMessage().isEmpty()?"mensagem não informada":item.getMessage()),Toast.LENGTH_LONG).show();break;}}});viewModel.getShortsProject().observe(this,p->{if(pipelineStarted&&p!=null&&!p.getCandidates().isEmpty()){binding.toolbar.setTitle("Melhores cortes");viewModel.prepareShorts(viewModel.getSelectedQueueItem().getValue());getSupportFragmentManager().beginTransaction().replace(R.id.contentHost,new ShortsReviewFragment()).commit();}});}
    private String safePublicUrl(String value){try{Uri u=Uri.parse(value);return (u.getScheme()==null?"":u.getScheme()+"://")+(u.getHost()==null?"":u.getHost())+(u.getPath()==null?"":u.getPath());}catch(Exception e){return "";}}
    private boolean isVertical(Uri u){try{MediaMetadataRetriever r=new MediaMetadataRetriever();r.setDataSource(this,u);int w=Integer.parseInt(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH));int h=Integer.parseInt(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT));r.release();return h>w;}catch(Exception e){return false;}}
}
