package com.serhat.autosub.cortaja.longvod;

public enum LongVodStage {
    RESOLVING, PREPARING_BLOCK, DOWNLOADING_AUDIO, VALIDATING_AUDIO, TRANSCRIBING,
    SAVING_TRANSCRIPT, ANALYZING_MOMENTS, RANKING, COMPLETED, FAILED
}
